import JSZip from 'jszip';
import { z } from 'zod';
import type { ThemeIndexRecord, VsixPayloadRecord } from '@/types/theme';

export const buildInputSchema = z.object({
  publisher: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  name: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  displayName: z.string().min(2),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  description: z.string().min(4),
});

export type VsixBuildInput = z.infer<typeof buildInputSchema>;

export interface BuiltVsixArtifact {
  filename: string;
  blob: Blob;
  mode: 'exact' | 'fallback';
}

function safeThemeFilename(name: string): string {
  return `${name.replace(/[^a-z0-9-]/g, '-')}.json`;
}

export async function buildVsixArtifact(
  input: VsixBuildInput,
  record: ThemeIndexRecord,
  payload: VsixPayloadRecord,
): Promise<BuiltVsixArtifact> {
  buildInputSchema.parse(input);

  const themeFileName = safeThemeFilename(input.name);
  const packageJson = {
    name: input.name,
    displayName: input.displayName,
    description: input.description,
    version: input.version,
    publisher: input.publisher,
    engines: {
      vscode: '^1.70.0',
    },
    categories: ['Themes'],
    contributes: {
      themes: [
        {
          label: record.themeDisplayName,
          uiTheme: payload.uiTheme,
          path: `./themes/${themeFileName}`,
        },
      ],
    },
  };

  const zip = new JSZip();
  zip.file('package.json', JSON.stringify(packageJson, null, 2));
  zip.file(`themes/${themeFileName}`, JSON.stringify(payload.themeJson, null, 2));
  zip.file('README.md', `# ${input.displayName}\n\nGenerated by ThemeDatabase (${payload.mode} mode).\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  return {
    filename: `${input.publisher}.${input.name}-${input.version}.vsix`,
    blob,
    mode: payload.mode,
  };
}
