import JSZip from 'jszip';
import { z } from 'zod';
import type { ThemeIndexRecord, VsixPayloadRecord } from '@/types/theme';

export const buildInputSchema = z.object({
  publisher: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  name: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  displayName: z.string().min(2),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  description: z.string().min(4),
});

export type VsixBuildInput = z.infer<typeof buildInputSchema>;

export interface BuiltVsixArtifact {
  filename: string;
  blob: Blob;
  mode: 'exact' | 'fallback';
}

function safeThemeFilename(name: string): string {
  return `${name.replace(/[^a-z0-9-]/g, '-')}.json`;
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

export async function buildVsixArtifact(
  input: VsixBuildInput,
  record: ThemeIndexRecord,
  payload: VsixPayloadRecord,
): Promise<BuiltVsixArtifact> {
  buildInputSchema.parse(input);

  const themeFileName = safeThemeFilename(input.name);
  const packageJson = {
    name: input.name,
    displayName: input.displayName,
    description: input.description,
    version: input.version,
    publisher: input.publisher,
    engines: {
      vscode: '^1.70.0',
    },
    categories: ['Themes'],
    contributes: {
      themes: [
        {
          label: record.themeDisplayName,
          uiTheme: payload.uiTheme,
          path: `./themes/${themeFileName}`,
        },
      ],
    },
  };

  const zip = new JSZip();
  const manifestXml = `<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Language="en-US" Id="${escapeXml(`${input.publisher}.${input.name}`)}" Version="${escapeXml(input.version)}" Publisher="${escapeXml(input.publisher)}" />
    <DisplayName>${escapeXml(input.displayName)}</DisplayName>
    <Description xml:space="preserve">${escapeXml(input.description)}</Description>
    <Tags>theme</Tags>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
  </Assets>
</PackageManifest>
`;

  const contentTypesXml = `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json" />
  <Default Extension="md" ContentType="text/markdown" />
  <Default Extension="vsixmanifest" ContentType="text/xml" />
</Types>
`;

  zip.file('[Content_Types].xml', contentTypesXml);
  zip.file('extension.vsixmanifest', manifestXml);
  zip.file('extension/package.json', JSON.stringify(packageJson, null, 2));
  zip.file(`extension/themes/${themeFileName}`, JSON.stringify(payload.themeJson, null, 2));
  zip.file('extension/README.md', `# ${input.displayName}\n\nGenerated by ThemeDatabase (${payload.mode} mode).\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  return {
    filename: `${input.publisher}.${input.name}-${input.version}.vsix`,
    blob,
    mode: payload.mode,
  };
}
