import JSZip from 'jszip';
import { z } from 'zod';
import type { ThemeIndexRecord, VsixPayloadRecord } from '@/types/theme';
import type { BuiltArtifact } from '@/types/export';

export const buildInputSchema = z.object({
  publisher: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  name: z.string().min(2).regex(/^[a-z0-9][a-z0-9-]*$/),
  displayName: z.string().min(2),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  description: z.string().min(4),
});

export type VsixBuildInput = z.infer<typeof buildInputSchema>;

function safeThemeFilename(name: string): string {
  return `${name.replace(/[^a-z0-9-]/g, '-')}.json`;
}

function safeSlug(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 70);
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

export async function buildVsixArtifact(
  input: VsixBuildInput,
  record: ThemeIndexRecord,
  payload: VsixPayloadRecord,
): Promise<BuiltArtifact> {
  buildInputSchema.parse(input);

  const themeFileName = safeThemeFilename(input.name);
  const packageJson = {
    name: input.name,
    displayName: input.displayName,
    description: input.description,
    version: input.version,
    publisher: input.publisher,
    engines: {
      vscode: '^1.70.0',
    },
    categories: ['Themes'],
    contributes: {
      themes: [
        {
          label: record.themeDisplayName,
          uiTheme: payload.uiTheme,
          path: `./themes/${themeFileName}`,
        },
      ],
    },
  };

  const zip = new JSZip();
  const manifestXml = `<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Language="en-US" Id="${escapeXml(`${input.publisher}.${input.name}`)}" Version="${escapeXml(input.version)}" Publisher="${escapeXml(input.publisher)}" />
    <DisplayName>${escapeXml(input.displayName)}</DisplayName>
    <Description xml:space="preserve">${escapeXml(input.description)}</Description>
    <Tags>theme</Tags>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
  </Assets>
</PackageManifest>
`;

  const contentTypesXml = `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json" />
  <Default Extension="md" ContentType="text/markdown" />
  <Default Extension="vsixmanifest" ContentType="text/xml" />
</Types>
`;

  zip.file('[Content_Types].xml', contentTypesXml);
  zip.file('extension.vsixmanifest', manifestXml);
  zip.file('extension/package.json', JSON.stringify(packageJson, null, 2));
  zip.file(`extension/themes/${themeFileName}`, JSON.stringify(payload.themeJson, null, 2));
  zip.file('extension/README.md', `# ${input.displayName}\n\nGenerated by ThemeDatabase (${payload.mode} mode).\n`);

  const blob = await zip.generateAsync({ type: 'blob' });
  return {
    target: 'vscode-vsix',
    filename: `${input.publisher}.${input.name}-${input.version}.vsix`,
    blob,
    mode: payload.mode,
  };
}

export async function buildVsixPackArtifact(
  input: VsixBuildInput,
  items: Array<{ record: ThemeIndexRecord; payload: VsixPayloadRecord }>,
): Promise<BuiltArtifact> {
  buildInputSchema.parse(input);
  if (items.length === 0) {
    throw new Error('No themes selected');
  }

  const containsFallback = items.some((x) => x.payload.mode !== 'exact');
  const mode: BuiltArtifact['mode'] = containsFallback ? 'fallback' : 'exact';

  const used = new Set<string>();
  const themeEntries = items.map(({ record, payload }, index) => {
    const base = safeSlug(`${input.name}-${record.themeInternalName || record.id || index}`);
    let slug = base || safeSlug(`${input.name}-${index + 1}`) || String(index + 1);
    let attempt = 1;
    while (used.has(slug)) {
      attempt += 1;
      slug = `${base}-${attempt}`;
    }
    used.add(slug);
    const filename = safeThemeFilename(slug);
    return {
      record,
      payload,
      filename,
    };
  });

  const packageJson = {
    name: input.name,
    displayName: input.displayName,
    description: input.description,
    version: input.version,
    publisher: input.publisher,
    engines: {
      vscode: '^1.70.0',
    },
    categories: ['Themes'],
    contributes: {
      themes: themeEntries.map((entry) => ({
        label: entry.record.themeDisplayName,
        uiTheme: entry.payload.uiTheme,
        path: `./themes/${entry.filename}`,
      })),
    },
  };

  const zip = new JSZip();
  const manifestXml = `<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Language="en-US" Id="${escapeXml(`${input.publisher}.${input.name}`)}" Version="${escapeXml(input.version)}" Publisher="${escapeXml(input.publisher)}" />
    <DisplayName>${escapeXml(input.displayName)}</DisplayName>
    <Description xml:space="preserve">${escapeXml(input.description)}</Description>
    <Tags>theme</Tags>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code" />
  </Installation>
  <Dependencies />
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
  </Assets>
</PackageManifest>
`;

  const contentTypesXml = `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json" />
  <Default Extension="md" ContentType="text/markdown" />
  <Default Extension="vsixmanifest" ContentType="text/xml" />
</Types>
`;

  zip.file('[Content_Types].xml', contentTypesXml);
  zip.file('extension.vsixmanifest', manifestXml);
  zip.file('extension/package.json', JSON.stringify(packageJson, null, 2));

  for (const entry of themeEntries) {
    zip.file(`extension/themes/${entry.filename}`, JSON.stringify(entry.payload.themeJson, null, 2));
  }

  const list = themeEntries.map((entry) => `- ${entry.record.themeDisplayName}`).join('\n');
  zip.file(
    'extension/README.md',
    `# ${input.displayName}\n\nGenerated by ThemeDatabase (${mode} mode).\n\nIncluded themes:\n${list}\n`,
  );

  const blob = await zip.generateAsync({ type: 'blob' });
  return {
    target: 'vscode-vsix',
    filename: `${input.publisher}.${input.name}-${input.version}.vsix`,
    blob,
    mode,
    meta: {
      themesCount: String(themeEntries.length),
      containsFallback: containsFallback ? 'true' : 'false',
    },
  };
}
