import type { BuiltArtifact } from '@/types/export';
import type { PlannedCatalog } from '@/exports/plan';
import { parseCssColor, rgbaToHexHash } from '@/lib/resolveColor';

export interface EmacsExportInput {
  filenameBase: string; // slug base
  displayName: string;
  mode: 'exact' | 'fallback';
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50) || 'theme';
}

function toHex(raw: string | undefined): string | null {
  if (!raw) return null;
  const parsed = parseCssColor(raw);
  if (!parsed) return null;
  if (parsed.a < 0.999) return null;
  return rgbaToHexHash(parsed);
}

export async function buildEmacsArtifact(input: EmacsExportInput, planned: PlannedCatalog): Promise<BuiltArtifact> {
  const byKey = new Map(planned.plan.included.map((f) => [f.key, f.value] as const));
  const get = (key: string): string | null => toHex(byKey.get(key));

  const slug = slugify(input.filenameBase);
  const themeSym = slug.replace(/-/g, '_');

  const faceLines: string[] = [];
  const addFace = (face: string, props: Record<string, string | null>) => {
    const entries = Object.entries(props)
      .filter(([, v]) => Boolean(v))
      .map(([k, v]) => `:${k} "${v}"`)
      .join(' ');
    if (!entries) return;
    faceLines.push(`   '(${face} ((t (${entries})))))`);
  };

  addFace('default', { background: get('default.bg'), foreground: get('default.fg') });
  addFace('cursor', { background: get('cursor.bg') });
  addFace('region', { background: get('region.bg') });
  addFace('font-lock-comment-face', { foreground: get('font-lock-comment-face.fg') });
  addFace('font-lock-string-face', { foreground: get('font-lock-string-face.fg') });
  addFace('font-lock-keyword-face', { foreground: get('font-lock-keyword-face.fg') });
  addFace('font-lock-function-name-face', { foreground: get('font-lock-function-name-face.fg') });
  addFace('font-lock-variable-name-face', { foreground: get('font-lock-variable-name-face.fg') });
  addFace('font-lock-type-face', { foreground: get('font-lock-type-face.fg') });
  addFace('font-lock-constant-face', { foreground: get('font-lock-constant-face.fg') });
  addFace('font-lock-builtin-face', { foreground: get('font-lock-builtin-face.fg') });

  const content =
    `;;; ${slug}-theme.el --- ${input.displayName} -*- lexical-binding: t; -*-\n\n` +
    `;; Generated by ThemeDatabase (${input.mode} mode)\n\n` +
    `(deftheme ${themeSym} "${input.displayName}")\n\n` +
    `(custom-theme-set-faces\n` +
    ` '${themeSym}\n` +
    `${faceLines.join('\n')}\n` +
    ` )\n\n` +
    `(provide-theme '${themeSym})\n\n` +
    `;;; ${slug}-theme.el ends here\n`;

  return {
    target: planned.plan.target,
    filename: `${slug}-theme.el`,
    blob: new Blob([content], { type: 'text/plain' }),
    mode: input.mode,
  };
}
