import type { TargetFieldDef } from '@/exports/catalogTypes';
import { resolveFromTokenRole, resolveFromVsCodeColorKeys } from '@/lib/resolveColor';

export const JETBRAINS_FIELDS: TargetFieldDef[] = [
  {
    key: 'TEXT.BACKGROUND',
    group: 'Editor',
    labelKey: 'export.field.editorBackground',
    alpha: 'forbidden',
    quickTweak: 'editorBackground',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editor.background']),
  },
  {
    key: 'TEXT.FOREGROUND',
    group: 'Editor',
    labelKey: 'export.field.editorForeground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editor.foreground']),
  },
  {
    key: 'CARET_COLOR',
    group: 'Editor',
    labelKey: 'export.field.caret',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorCursor.foreground']),
  },
  {
    key: 'SELECTION_BACKGROUND',
    group: 'Editor',
    labelKey: 'export.field.selectionBackground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editor.selectionBackground']),
  },
  {
    key: 'SELECTION_FOREGROUND',
    group: 'Editor',
    labelKey: 'export.field.selectionForeground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editor.selectionForeground']),
  },
  {
    key: 'CURRENT_LINE',
    group: 'Editor',
    labelKey: 'export.field.currentLine',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editor.lineHighlightBackground']),
  },
  {
    key: 'INDENT_GUIDE',
    group: 'Editor',
    labelKey: 'export.field.indentGuide',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorIndentGuide.background']),
  },
  {
    key: 'INDENT_GUIDE_ACTIVE',
    group: 'Editor',
    labelKey: 'export.field.indentGuideActive',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorIndentGuide.activeBackground']),
  },
  {
    key: 'LINE_NUMBERS',
    group: 'Editor',
    labelKey: 'export.field.lineNumbers',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorLineNumber.foreground']),
  },
  {
    key: 'LINE_NUMBERS_ACTIVE',
    group: 'Editor',
    labelKey: 'export.field.lineNumbersActive',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorLineNumber.activeForeground']),
  },
  {
    key: 'GUTTER_BACKGROUND',
    group: 'Editor',
    labelKey: 'export.field.gutterBackground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['editorGutter.background']),
  },
  {
    key: 'LINE_COMMENT.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.comment',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'comment'),
  },
  {
    key: 'BLOCK_COMMENT.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.blockComment',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'comment'),
  },
  {
    key: 'STRING.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.string',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'string'),
  },
  {
    key: 'NUMBER.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.number',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'number'),
  },
  {
    key: 'KEYWORD.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.keyword',
    alpha: 'forbidden',
    quickTweak: 'accentColor',
    resolve: (source) => resolveFromTokenRole(source, 'keyword'),
  },
  {
    key: 'FUNCTION_DECLARATION.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.function',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'function'),
  },
  {
    key: 'LOCAL_VARIABLE.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.variable',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'variable'),
  },
  {
    key: 'TYPE.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.type',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'type'),
  },
  {
    key: 'OPERATION_SIGN.FOREGROUND',
    group: 'Syntax',
    labelKey: 'export.field.operator',
    alpha: 'forbidden',
    resolve: (source) => resolveFromTokenRole(source, 'operator'),
  },
  {
    key: 'CONSOLE.BACKGROUND',
    group: 'Console',
    labelKey: 'export.field.consoleBackground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.background']),
  },
  {
    key: 'CONSOLE.FOREGROUND',
    group: 'Console',
    labelKey: 'export.field.consoleForeground',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.foreground']),
  },
  {
    key: 'CONSOLE.ANSI_BLACK',
    group: 'Console',
    labelKey: 'export.field.ansiBlack',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBlack']),
  },
  {
    key: 'CONSOLE.ANSI_RED',
    group: 'Console',
    labelKey: 'export.field.ansiRed',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiRed']),
  },
  {
    key: 'CONSOLE.ANSI_GREEN',
    group: 'Console',
    labelKey: 'export.field.ansiGreen',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiGreen']),
  },
  {
    key: 'CONSOLE.ANSI_YELLOW',
    group: 'Console',
    labelKey: 'export.field.ansiYellow',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiYellow']),
  },
  {
    key: 'CONSOLE.ANSI_BLUE',
    group: 'Console',
    labelKey: 'export.field.ansiBlue',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBlue']),
  },
  {
    key: 'CONSOLE.ANSI_MAGENTA',
    group: 'Console',
    labelKey: 'export.field.ansiMagenta',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiMagenta']),
  },
  {
    key: 'CONSOLE.ANSI_CYAN',
    group: 'Console',
    labelKey: 'export.field.ansiCyan',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiCyan']),
  },
  {
    key: 'CONSOLE.ANSI_WHITE',
    group: 'Console',
    labelKey: 'export.field.ansiWhite',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiWhite']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_BLACK',
    group: 'Console',
    labelKey: 'export.field.ansiBrightBlack',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightBlack']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_RED',
    group: 'Console',
    labelKey: 'export.field.ansiBrightRed',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightRed']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_GREEN',
    group: 'Console',
    labelKey: 'export.field.ansiBrightGreen',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightGreen']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_YELLOW',
    group: 'Console',
    labelKey: 'export.field.ansiBrightYellow',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightYellow']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_BLUE',
    group: 'Console',
    labelKey: 'export.field.ansiBrightBlue',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightBlue']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_MAGENTA',
    group: 'Console',
    labelKey: 'export.field.ansiBrightMagenta',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightMagenta']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_CYAN',
    group: 'Console',
    labelKey: 'export.field.ansiBrightCyan',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightCyan']),
  },
  {
    key: 'CONSOLE.ANSI_BRIGHT_WHITE',
    group: 'Console',
    labelKey: 'export.field.ansiBrightWhite',
    alpha: 'forbidden',
    resolve: (source) => resolveFromVsCodeColorKeys(source, ['terminal.ansiBrightWhite']),
  },
];

